---
- name: playbook to create new user
  hosts: all
  #gather_facts: no
  become: true
  #vars:
    #user_name: ini
  vars_files:
    - /home/ansadmin/playbooks/new_user.txt


  tasks:
    - name: creating user {{user_name}}
      user: 
        name: "{{user_name}}"

    - name: create temp directory for new user - {{user_name}} 
      file:
        path: /opt/{{ user_name}}_tmp_dir
        state: directory
        owner: "{{ user_name }}"
        group: "{{user_name}}"
        mode: 0755
