---
- name: create files or directories
  hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: create file
      file: 
        path: /home/ansadmin/testdir
        #state: touch # creats file
        #owner: tunmise
        #group: 
        state: directory # creates directory
        mode: 0755
