---
- name: git module demo
  hosts: all
  gather_facts: yes
  vars:
    repo: "git@github.com:ooje2022/vault.git"
    dest: "/home/ansadmin/vault"
    sshkey: "home/ansadmin/.ssh/authorized_keys" # "~/.ssh/id_rsa"
  tasks:
    - name: ensure git pkg installed Redhat
      ansible.builtin.yum:
        name: git
        state: present
        update_cache: true
      become: true
      when: ansible_os_family == "RedHat"

    - name: ensure git pkg installed Debian
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: true
      become: true
      when: ansible_os_family == "Debian"

    - name: checkout git repo
      ansible.builtin.git:
        repo: "{{ repo }}"
        dest: "{{ dest }}"
        key_file: "{{ sshkey }}"
