---
- name: install multiple packages
  hosts: all
  become: true
  gather_facts: yes


  tasks:
    - name: install packages
      yum:
        name: ['git', 'wget', 'tree', 'make', 'telnet', 'gzip']
        state: installed
