---
# tasks file for tomcat_setup
- name: create user {{ user_name }}
  user:
    name: "{{ user_name }}"
    state: present

- name: install javajdk on REDHAT
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - java-11-openjdk-devel
  when: ansible_os_family == "RedHat"

- name: install javajdk on DEBIAN / UBUNTU
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - openjdk-11-jdk
  when: ansible_os_family == "Debian"

- name: download apache tomcat package
  get_url:
    url: "{{ tomcat_url }}"
    dest: /opt
    mode: 0755

- name: extract file from tar/zip packages
  unarchive:
    src: /opt/{{ tomcat_package }}.tar.gz #
    dest: /opt
    remote_src: yes

- name: grant permissions to user to read, write and execute tomcat folderss
  file:
    path: /opt/{{ tomcat_package }}
    mode: 0755
    recurse: yes

- name: create link file to startup.sh
  file:
    src: /opt/{{ tomcat_package }}/bin/{{ item.tomcat_script }}
    dest: /usr/local/bin/{{ item.tomcat_cmd }}
    state: link
  loop:
    - { tomcat_script: startup.sh, tomcat_cmd: tomcatup }
    - { tomcat_script: shutdown.sh, tomcat_cmd: tomcatdown }
  notify: start tomcat

- name: change port number
  copy:
    src: server.xml
    dest: /opt/{{tomcat_package }}/conf/server.xml
  notify: restart tomcat

